//! GENERATED by `cargo run --release -p fsci-linalg --bin casp_calibrate` (frankenscipy-7tb8d.2).
//! Do not edit: regenerate it and commit it with `artifacts/casp-calibration-solver.json`,
//! whose `loss_matrix` a test compares with these values bit for bit.
//!
//! Corpus version 1, seed 0x7b8d0002ca11b8a7: 324 matrices at n = 8, 32 and 128.
//! loss(a, s) = cost(a) + E[recovery cost of a failure of a | s]. A failure is what makes the
//! portfolio fall back (an error, a non-finite answer or a backward error above
//! `ATTEMPT_BACKWARD_ERROR_TOL`), recovered at the cost of the cheapest action that succeeds
//! on that matrix; cost is leading-order flops relative to LU.

/// `SolverPortfolio`'s loss matrix: one row per action in `SolverAction::ALL` order, one
/// column per state (well conditioned, moderate, ill conditioned, near singular).
#[rustfmt::skip]
pub(crate) const SOLVER_LOSS_MATRIX: [[f64; 4]; 6] = [
    [1.0319926099000587, 1.0006762508973737, 1.0, 1.0], // DirectLU
    [2.0, 2.0, 2.0, 2.0], // PivotedQR
    [31.5, 31.5021466321814, 31.727013976223127, 32.201463282742864], // SVDFallback
    [0.0, 0.0, 0.0, 0.0], // DiagonalFastPath
    [0.0, 0.0, 0.0, 0.0], // TriangularFastPath
    [0.5, 0.5, 0.5, 0.5], // SymmetricFastPath
];

/// Each action's cost in the loss: leading-order flops relative to LU.
#[rustfmt::skip]
pub(crate) const SOLVER_ACTION_COST: [f64; 6] = [1.0, 2.0, 31.5, 0.0, 0.0, 0.5];

/// The measured failure rate of each action in each state (state-weighted over the
/// corpus; an unmeasured pair is 1).
#[rustfmt::skip]
pub(crate) const SOLVER_FAILURE_RATE: [[f64; 4]; 6] = [
    [0.01599630495002933, 0.0003381254486868826, 0.0, 0.0], // DirectLU
    [0.0, 0.0, 0.0, 0.0], // PivotedQR
    [0.0, 0.0021466321814016215, 0.266468452116023, 0.9163039559984879], // SVDFallback
    [0.0, 0.0, 0.0, 0.0], // DiagonalFastPath
    [0.0, 0.0, 0.0, 0.0], // TriangularFastPath
    [0.0, 0.0, 0.0, 0.0], // SymmetricFastPath
];
