[package]
name = "fsci-special"
version = "0.1.0"
edition = "2024"

[dependencies]
fsci-integrate = { workspace = true }
fsci-linalg = { workspace = true }
fsci-runtime = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
sha2 = "0.10.9"

[[bench]]
name = "special_bench"
harness = false
